services:

  backend:
    container_name: mk_burger_api
    build:
      dockerfile: Dockerfile.dev
    image: mk_burger_api:latest
    volumes:
      - ./:/home/app/
    restart: 'no'
    stdin_open: true   # Add this line into your service
    tty: true   # Add this line into your service
    env_file:
      - .env
    environment:
      - PYTHONBREAKPOINT=ipdb.set_trace
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    container_name: mk_burger_db
    image: postgres:16.1-alpine
    restart: 'no'
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=mk_burger_user
      - POSTGRES_DB=mk_burger_db
    ports:
      - 5432:5432

volumes:
  pg_data:
